version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 18...
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      - sudo apt-get install -y nodejs

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm insatall
  build:
    commands:
      - echo Building se construye..
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public
